"""Purpose notes for scripts/envdoc.py — one line per variable, written from the code that reads it.

Keep each note true to the reading site (grep the file in the table before editing).
A variable missing here still appears in the generated table with purpose "—", and tests/test_docs.py fails.
"""

NOTES = {
    # ── rover link / SDK ──────────────────────────────────────────────────────
    "ROVER_SDK_URL": "Where every tool and the cockpit find the Earth Rovers SDK (`http://localhost:8002` locally, `http://sdk:8002` in compose).",
    "ROVER_HTTP_TIMEOUT": "Seconds before an SDK HTTP call in `_rover_common` gives up.",
    "ROVER_TURN_SIGN": "Flip (`-1`) the agent tools' angular sign if the rover turns the wrong way; independent from the cockpit's `DASH_TURN_SIGN`.",
    "ROVER_AGENT_ID": "Persona/agent id folded into the per-day dataset path so several processes append to their own sub-dataset.",
    "ROVER_REPO_ID": "Pin one growing LeRobot dataset id; unset = a new `scout__earth-rover-mini-YYYYMMDD` per day.",
    "ROVER_DATASET_ROOT": "Root directory for LeRobot datasets (default `datasets/`) — recorder and replay API.",
    "ROVER_RECORD_FPS": "Dataset frame rate (10 — the earthrover_mini_plus convention).",
    "ROVER_RECORD_WIDTH": "Recorded frame width (640).",
    "ROVER_RECORD_HEIGHT": "Recorded frame height (480).",
    "ROVER_RECORD_REAR": "`1` (default) also records the rear camera as `observation.images.rear`; `0` = front-only datasets.",
    "ROVER_AUDIO_RATE": "Sample rate of the recorded mic track (16 kHz).",
    "ROVER_REJECT_BLACK_FRAMES": "Drop frames whose pixel std-dev is below `ROVER_BLACK_FRAME_STD` (camera not yet streaming).",
    "ROVER_BLACK_FRAME_STD": "Std-dev threshold under which a frame counts as black.",
    "ROVER_MIN_FRAME_DIM": "Reject frames smaller than this many pixels on a side (placeholder images).",
    "ROVER_RECORD_ERROR_LOG_PERIOD": "Seconds between repeated 'capture frame error' log lines (anti-spam).",
    "ROVER_RECORDER_DEBUG": "`1` prints the macOS SDL2/objc duplicate-dylib warnings instead of spooling them to a file.",
    "ROVER_RECORDER_LOG": "Where those swallowed SDL warnings go (default `/tmp/rover_recorder_sdl.log`).",
    "ROVER_CONTROLLER_HZ": "PS4 teleop: `/control` frames per second while sticks are held.",
    "ROVER_CONTROLLER_LINEAR_MAX": "PS4 teleop: cap on |linear| (0.7).",
    "ROVER_CONTROLLER_ANGULAR_MAX": "PS4 teleop: cap on |angular| (0.9).",
    "ROVER_CONTROLLER_DEADZONE": "PS4 teleop: stick dead-zone (0.08).",
    "ROVER_CONTROLLER_DEBUG": "`1` surfaces pygame/SDL warnings on stderr.",
    "ROVER_CONTROLLER_LOG": "Spool file for those warnings.",
    "ROVER_AEC_RATE": "Voice (rover audio): pywebrtc echo-canceller sample rate (48 kHz; the model runs at 24 kHz).",
    "ROVER_AEC_DELAY_MS": "Voice: far-end delay hint for AEC — the rover's speaker→mic round trip (150 ms).",
    "ROVER_GATE_TAIL_S": "Voice: how long the mic stays muted after the model stops speaking (half-duplex gate tail, 0.6 s).",
    # ── models ────────────────────────────────────────────────────────────────
    "STRANDS_MODEL_ID": "Bedrock model id for every text persona; editable live from the cockpit ⚙️ drawer.",
    "AWS_REGION": "Bedrock region for the text model and Nova Sonic voice.",
    "OPENAI_API_KEY": "OpenAI Realtime key for `VOICE_PROVIDER=openai`.",
    "GOOGLE_API_KEY": "Gemini Live key (`VOICE_PROVIDER=gemini`); `GEMINI_API_KEY` is the alternative name.",
    "GEMINI_API_KEY": "Alternative to `GOOGLE_API_KEY` for Gemini Live.",
    "HF_TOKEN": "Hugging Face token for model downloads during the GPU image warm-up.",
    "C3_MODEL": "GPU stack: Cosmos 3 reasoner HF id to pre-download (default `nvidia/Cosmos3-Nano`).",
    "C3_GEN_MODEL": "GPU stack: Cosmos 3 generator HF id to pre-download.",
    # ── voice ─────────────────────────────────────────────────────────────────
    "VOICE_PROVIDER": "`openai` · `nova_sonic` · `gemini` — which bidi speech model the voice persona builds.",
    "VOICE_MODEL": "Realtime model id override (e.g. `gpt-realtime-2`).",
    "VOICE_NAME": "Voice inside the provider (`marin`, `shimmer`, `matthew`, `Kore`…).",
    "VOICE_AUDIO": "`laptop` (local mic/speakers) or `rover` (the rover's mic + speaker over the SDK) — default for `--audio`.",
    "SCOUT_BRIEFING_DEBOUNCE_S": "Voice bridge: coalesce briefings that arrive within this window into one text turn (4 s).",
    "SCOUT_BRIEFING_MAX_HOLD_S": "Voice bridge: never hold a briefing longer than this while waiting for a quiet moment (20 s).",
    "SCOUT_BRIEFING_GATE_TIMEOUT_S": "Voice bridge: give up waiting for the in-flight response to end after this many seconds (15 s).",
    "SCOUT_BRIEFING_MUTE_SOURCES": "Comma list of personas whose briefings are dropped unless URGENT (compose default `thinker`).",
    # ── listener (Whisper trigger) ────────────────────────────────────────────
    "LISTENER_DISABLED": "`1` = the listener loop exits immediately.",
    "LISTENER_WAKE_WORD": "Only trigger when the transcript contains this phrase (e.g. `hey scout`).",
    "LISTENER_MIN_CHARS": "Ignore transcripts shorter than this.",
    "LISTENER_ENERGY_THRESHOLD": "RMS (0..1) above which a frame counts as speech.",
    "LISTENER_SILENCE_SEC": "Trailing silence that ends an utterance.",
    "LISTENER_MAX_SEG_SEC": "Hard cap on a single utterance.",
    "LISTENER_MIN_SEG_SEC": "Drop segments shorter than this.",
    "LISTENER_WHISPER_MODEL": "faster-whisper model id (`base.en`).",
    "LISTENER_COOLDOWN_SEC": "Minimum gap between two agent triggers.",
    "LISTENER_MIC_RATE": "Mic sample rate the listener drains at (16 kHz).",
    "LISTENER_CUDA": "`cpu` forces CPU inference; anything else tries CUDA.",
    "LISTENER_VAD_AGGRESSIVENESS": "webrtcvad aggressiveness 0–3.",
    "LISTENER_USE_HUB": "`1` (default) reads the mic through the MediaHub instead of draining `/rover-mic` directly.",
    # ── telegram ──────────────────────────────────────────────────────────────
    "SCOUT_TELEGRAM_BOT_TOKEN": "Bot token from @BotFather (preferred name).",
    "TELEGRAM_BOT_TOKEN": "Legacy name for `SCOUT_TELEGRAM_BOT_TOKEN`.",
    "SCOUT_TELEGRAM_DEFAULT_CHAT_ID": "Chat the `telegram` tool and the thinker post to when none is given.",
    "TELEGRAM_DEFAULT_CHAT_ID": "Legacy name for `SCOUT_TELEGRAM_DEFAULT_CHAT_ID`.",
    "SCOUT_TELEGRAM_ALLOWED_USERS": "Comma list of Telegram user ids allowed to command the rover (empty = anyone — don't).",
    "TELEGRAM_ALLOWED_USERS": "Legacy name for `SCOUT_TELEGRAM_ALLOWED_USERS`.",
    "SCOUT_TELEGRAM_HISTORY_LIMIT": "How many past messages the Telegram persona keeps in context.",
    "TELEGRAM_HISTORY_LIMIT": "Legacy name for `SCOUT_TELEGRAM_HISTORY_LIMIT`.",
    # ── thinker ───────────────────────────────────────────────────────────────
    "THINKER_INTERVAL": "Seconds between thinker cycles (60).",
    "THINKER_DISABLED": "`1` makes the loop a no-op (debugging).",
    "THINKER_TELEGRAM_CHAT_ID": "Chat the thinker may post photos/updates to (falls back to the default chat id).",
    # ── personas / supervisor ─────────────────────────────────────────────────
    "SCOUT_PERSONA": "Which persona this process is (`thinker`, `voice`, `telegram`, `dashboard`…) — the thinker drive gate keys on it.",
    "SCOUT_PERSONA_FLAGS": "Path of the shared flags file (`.memory/personas.json`: `thinker_drive`, `recording`).",
    "SCOUT_SUPERVISOR_SOCK": "Unix socket where the dashboard reaches the host-side supervisor.",
    "SCOUT_SUPERVISOR_TOKEN": "Shared secret both the dashboard and the supervisor read; sent as `X-Scout-Supervisor-Token`.",
    "SCOUT_SUPERVISOR_DIR": "Supervisor: where the socket and `audit.log` live (default `<repo>/.supervisor`).",
    "SCOUT_REPO": "Supervisor: the compose project directory it runs `docker compose` in.",
    # ── perception ────────────────────────────────────────────────────────────
    "MEDIA_HUB_PORT": "MediaHub listen port (8090).",
    "MEDIA_HUB_URL": "Where clients find the hub (compose: `http://media:8090`).",
    "MEDIA_HUB_DEFAULT_URL": "Fallback hub URL when `MEDIA_HUB_URL` is unset.",
    "MEDIA_HUB_ENABLED": "`auto` · `on` · `off` — whether clients try the hub before polling the SDK directly.",
    "MEDIA_HUB_VIDEO_INTERVAL": "Seconds between camera pulls from the SDK (0.1 → ~10 fps).",
    "MEDIA_HUB_MIC_INTERVAL": "Seconds between mic buffer drains.",
    "MEDIA_HUB_DATA_INTERVAL": "Seconds between `/data` telemetry pulls.",
    "MEDIA_HUB_MIC_RATE": "Mic sample rate the hub republishes (16 kHz).",
    "MEDIA_HUB_REAR": "`1` also drains the rear camera stream.",
    "YOLO_MODEL": "Ultralytics weights (`yolov8n.pt`, auto-downloaded).",
    "YOLO_CONF": "Detection confidence threshold (0.35).",
    "YOLO_EVERY_N": "Run inference on every Nth hub frame (compose sets 2).",
    "YOLO_IMGSZ": "Inference image size (640).",
    "YOLO_DEVICE": "`cuda` · `cpu` · `auto`.",
    "YOLO_CAMERA": "`front` · `rear` · `both`.",
    "DET_BACKEND": "`yolo` (default) or `locate` (NVIDIA LocateAnything-3B open-vocabulary grounding).",
    "LOCATE_MODEL": "HF id for the locate backend.",
    "LOCATE_QUERY": "Natural-language grounding query for the locate backend (`person. chair. sofa. …`).",
    "LOCATE_ATTN": "Attention implementation for LocateAnything (`sdpa`).",
    "SCOUT_ENABLE_COSMOS": "`1`/`0` force the Cosmos tools on/off; `auto` = present when the package imports (GPU stack). Slim pins `0`.",
    "COSMOS_BUFFER_DIR": "Cosmos ring buffer: where finished clips are written.",
    "COSMOS_BUFFER_CAMERA": "Cosmos ring buffer: `front` or `rear`.",
    "COSMOS_CLIP_SECONDS": "Cosmos ring buffer: clip length.",
    "COSMOS_CLIP_FPS": "Cosmos ring buffer: encode fps.",
    "COSMOS_KEEP_CLIPS": "Cosmos ring buffer: how many clips to retain.",
    "SCOUT_ROOM_SCAN": "Path of the Apple RoomPlan `.usdz` the room-map tool parses (default `cagatay_lab.usdz`).",
    "SCOUT_LIN_SPEED_MAX": "Dead reckoning: m/s at `linear=1.0` (0.35).",
    "SCOUT_ANG_SPEED_MAX": "Dead reckoning: rad/s at `angular=1.0` (1.20).",
    "SCOUT_IMU_YAW_TRUST": "Dead reckoning: complementary-filter weight of IMU yaw (0 = ignore, 1 = trust fully).",
    "SCOUT_POSE_STALE_SECONDS": "Dead reckoning: pose flagged STALE after this long (30 min).",
    "SCOUT_POSE_DRIFT_BUDGET_M": "Dead reckoning: pose flagged STALE after this much travel (8 m).",
    "SCOUT_POSE_FILE": "Where the estimated pose is persisted between processes.",
    "SCOUT_CAL_FILE": "Where speed calibration is persisted.",
    "SCOUT_ASYNC_FRAME_INTERVAL": "`rover_async`: seconds between `/control` frames streamed by the background worker (0.35).",
    # ── datasets ──────────────────────────────────────────────────────────────
    "SCOUT_AUTO_RECORD": "`0` disables auto-recording of agent turns.",
    "SCOUT_AUTO_RECORD_MIN_ACTIONS": "Drop auto-recorded episodes with fewer than N motion actions (1).",
    "SCOUT_AUTO_RECORD_MAX_TASK_LEN": "Truncate the prompt stored as the episode task to this many chars (256).",
    "SCOUT_SEAL_EPISODES": "`1` (default) finalizes the dataset after every episode so it is readable mid-session; `0` = packed files, footer only at exit.",
    "SCOUT_DATASETS_DIR": "Dataset index: root to scan for the cockpit/agent list.",
    "SCOUT_DATASET_MAX_VIDEOS": "Dataset index: cap on video paths surfaced to the agent prompt.",
    "SCOUT_DATASET_MAX_TRACES": "Dataset index: cap on reasoning-trace paths surfaced.",
    "SCOUT_INJECT_DATASETS": "`1` injects the dataset index into the agent prompt (Cosmos tools need real paths).",
    "SCOUT_KEYFRAME_STRIDE": "Episode enrichment: keyframe every N frames.",
    "SCOUT_KEYFRAME_MOTION": "Episode enrichment: also keyframe when the action changes.",
    "SCOUT_YOLO_MODEL": "Episode enrichment: YOLO weights for offline detection.",
    "SCOUT_WHISPER_MODEL": "Episode enrichment: faster-whisper size for transcribing the mic track.",
    "SCOUT_CLIP_MODEL": "Memory index: CLIP model for image embeddings (`openai/clip-vit-base-patch32`).",
    "ECOT_EVENTS_DB": "ECoT export: override path of the reasoning events SQLite.",
    # ── memory ────────────────────────────────────────────────────────────────
    "SCOUT_MEMORY_DIR": "Directory of the shared SQLite brain (`.scout_memory` locally, `.memory` in compose).",
    "SCOUT_MEMORY_PROMPT_MAX": "Max chars of recalled memory injected into the system prompt.",
    "SCOUT_MEMORY_RECALL_TURNS": "How many recent turns to recall.",
    "SCOUT_MEMORY_REPLY_MAX": "Max chars of a reply stored per turn.",
    # ── cockpit ───────────────────────────────────────────────────────────────
    "DASH_HOST": "Bind address of the cockpit server.",
    "DASH_PORT": "Cockpit port (8080).",
    "DASH_TLS": "`true` serves HTTPS with a generated self-signed cert (WebAuthn needs it).",
    "DASH_TLS_DIR": "Where the generated cert/key are kept (compose: the auth volume).",
    "DASH_TLS_HOSTS": "Extra SANs to put in the generated cert (a private domain, `scout.local`).",
    "DASH_TLS_CERT": "Use this real certificate instead of generating one.",
    "DASH_TLS_KEY": "Private key matching `DASH_TLS_CERT`.",
    "DASH_TLS_MKCERT": "`auto` uses mkcert when installed for a locally-trusted cert.",
    "CAROOT": "mkcert CA root directory (mkcert's own variable), honoured when exporting `/ca`.",
    "DASH_TURN_SIGN": "Flip the joystick/WASD angular sign (default `-1`), independent from `ROVER_TURN_SIGN`.",
    "SCOUT_PUBLIC_URL": "Public URL printed on the field card / QR and used for links (else the request Host).",
    "SCOUT_MDNS_NAME": "mDNS name announced on the LAN (`scout` → `scout.local`).",
    # ── auth ──────────────────────────────────────────────────────────────────
    "SCOUT_AUTH_STORE": "Path of the passkey + JWT-secret store (`auth.json`, chmod 600).",
    "SCOUT_AUTH_RP_ID": "WebAuthn relying-party id — the public hostname when behind a tunnel.",
    "SCOUT_AUTH_RP_NAME": "Display name shown in the passkey prompt.",
    "SCOUT_AUTH_ORIGIN": "Expected WebAuthn origin (derived from the request when unset).",
    "SCOUT_AUTH_TOKEN_TTL": "Session JWT lifetime in seconds (24 h).",
    "SCOUT_AUTH_BOOTSTRAP_TOKEN": "One-time secret required to enrol the FIRST passkey — set it before exposing a fresh rover to the internet.",
    # ── fleet (tiny.technology MCP) ───────────────────────────────────────────
    "TINY_MCP": "`1` mounts the tiny.technology fleet tools into the agents (off by default).",
    "TINY_MCP_PERSONAS": "Comma list of personas that get fleet tools (default dashboard, telegram, shell).",
    "TINY_TOKEN": "tiny.technology user CLI JWT the MCP server authenticates with (lives in `.tiny-mcp.env`).",
    "TINY_TOKEN_FILE": "Read the token from a file instead (wins over `TINY_TOKEN`).",
    "TINY_MCP_COMMAND": "Full command to start the MCP server (overrides node/tiny-tech autodetection).",
    "TINY_MCP_NODE": "Path to the node binary.",
    "TINY_MCP_TINY_TECH": "Path to the tiny-tech package dir (image: `/opt/tiny-mcp/node_modules/tiny-tech`).",
    "TINY_MCP_HOME": "Isolated `TINY_HOME` for the server (default `~/.tiny-mcp`).",
    "TINY_MCP_MESH": "`1` lets the server join the zenoh mesh (off: CPU).",
    "TINY_MCP_TIMEOUT": "Per-tool-call read timeout in seconds (90).",
    "TINY_MCP_STARTUP_TIMEOUT": "Seconds to wait for the MCP server to come up (45).",
    "TINY_SELF_DEVICE_IDS": "This robot's own device ids/names — `use_device` refuses to invoke them.",
    "TINY_SELF_NAME": "Name stamped into the `[fleet depth=1 from <name>]` marker on outgoing fleet turns.",
}

GROUPS: dict[str, str] = {
    "CAROOT": "Dashboard", "HF_TOKEN": "Models", "C3_MODEL": "Models", "C3_GEN_MODEL": "Models",
    "ECOT_EVENTS_DB": "Datasets", "SCOUT_CLIP_MODEL": "Datasets", "SCOUT_KEYFRAME_STRIDE": "Datasets", "SCOUT_KEYFRAME_MOTION": "Datasets",
    "SCOUT_YOLO_MODEL": "Datasets", "SCOUT_WHISPER_MODEL": "Datasets", "SCOUT_INJECT_DATASETS": "Datasets",
    "SCOUT_MEMORY_DIR": "Scout", "SCOUT_MEMORY_PROMPT_MAX": "Scout", "SCOUT_MEMORY_RECALL_TURNS": "Scout", "SCOUT_MEMORY_REPLY_MAX": "Scout",
    "SCOUT_ROOM_SCAN": "Perception", "SCOUT_LIN_SPEED_MAX": "Perception", "SCOUT_ANG_SPEED_MAX": "Perception", "SCOUT_IMU_YAW_TRUST": "Perception",
    "SCOUT_POSE_STALE_SECONDS": "Perception", "SCOUT_POSE_DRIFT_BUDGET_M": "Perception", "SCOUT_POSE_FILE": "Perception", "SCOUT_CAL_FILE": "Perception",
    "SCOUT_ASYNC_FRAME_INTERVAL": "Rover", "SCOUT_REPO": "Personas", "SCOUT_PERSONA_FLAGS": "Personas",
    "ROVER_AEC_RATE": "Voice", "ROVER_AEC_DELAY_MS": "Voice", "ROVER_GATE_TAIL_S": "Voice", "VOICE_AUDIO": "Voice",
    "ROVER_REPO_ID": "Datasets", "ROVER_DATASET_ROOT": "Datasets", "ROVER_RECORD_FPS": "Datasets", "ROVER_RECORD_WIDTH": "Datasets", "ROVER_RECORD_HEIGHT": "Datasets",
    "ROVER_RECORD_REAR": "Datasets", "ROVER_AUDIO_RATE": "Datasets", "ROVER_REJECT_BLACK_FRAMES": "Datasets", "ROVER_BLACK_FRAME_STD": "Datasets",
    "ROVER_MIN_FRAME_DIM": "Datasets", "ROVER_RECORD_ERROR_LOG_PERIOD": "Datasets", "ROVER_RECORDER_DEBUG": "Datasets", "ROVER_RECORDER_LOG": "Datasets", "ROVER_AGENT_ID": "Datasets",
    "SCOUT_TELEGRAM_BOT_TOKEN": "Telegram", "SCOUT_TELEGRAM_DEFAULT_CHAT_ID": "Telegram", "SCOUT_TELEGRAM_ALLOWED_USERS": "Telegram", "SCOUT_TELEGRAM_HISTORY_LIMIT": "Telegram",
    "SCOUT_MDNS_NAME": "Dashboard", "DASH_TURN_SIGN": "Dashboard",
}
for _n in NOTES:
    if _n.startswith("LISTENER_"):
        GROUPS.setdefault(_n, "Voice")
    if _n.startswith("COSMOS_") or _n.startswith("LOCATE_") or _n.startswith("YOLO_") or _n.startswith("MEDIA_HUB") or _n == "DET_BACKEND":
        GROUPS.setdefault(_n, "Perception")
