"""One-line notes for routes whose handler has no docstring — keyed "METHOD /path". Keep true to the handler."""

NOTES = {
    "GET /": "The cockpit SPA shell (`docs/index.html`); the login/enrol screen loads from here.",
    "GET /replay": "The dataset replay page (`docs/replay.html`).",
    "GET /api/health": "Liveness: `{ok, sdk, …}` — the only `/api` route without a session.",
    "GET /api/telemetry": "The SDK's `/data` snapshot: battery, GPS, IMU, RPMs, lamp, signal.",
    "GET /api/config": "Current model id, voice provider/name, system prompt and masked env keys for the ⚙️ drawer.",
    "POST /api/control": "One drive frame `{linear, angular, duration}` in [-1, 1]; hold a stream of them to move (joystick/WASD).",
    "POST /api/lamp": "Headlamp on/off `{on}`.",
    "POST /api/speak": "Say `{text}` through the rover's onboard speaker (SDK `/speak`).",
    "GET /api/frame/{view}": "Latest JPEG for `front` or `rear` (proxied from the SDK / hub).",
    "GET /api/screenshot": "Composite screenshot of `views` (default `front,rear,map`) from the SDK.",
    "GET /api/personas": "Snapshot of every persona: container state (voice/thinker/telegram) + flags (thinker_drive, recording).",
    "GET /api/personas/{name}/logs": "Last lines of that persona container's logs via the host supervisor.",
    "GET /api/replay/datasets": "List datasets under the dataset root with episode counts and `index_state`.",
    "GET /api/replay/{ds_id}/episodes": "Episode index for a dataset (length, video window, task) with fallbacks when the parquet has no footer.",
    "GET /api/replay/{ds_id}/episode/{episode_index}": "One episode: state/action rows + the aligned reasoning trace.",
    "GET /api/replay/{ds_id}/video/{view}": "Stream the mp4 for a camera view; `?file=` selects the per-episode file.",
    "GET /api/replay/{ds_id}/memory/stats": "Counts for the dataset's memory/reasoning index.",
    "GET /auth/status": "`setup_required` (no passkeys yet), `enabled`, current session subject.",
    "POST /auth/register/begin": "Start a WebAuthn registration ceremony (first one may require the bootstrap token).",
    "POST /auth/register/finish": "Verify the attestation and store the new passkey's public key.",
    "POST /auth/login/begin": "Issue a login challenge.",
    "POST /auth/login/finish": "Verify the assertion and issue the session JWT.",
    "POST /auth/logout": "Drop the session.",
    "POST /auth/credentials/rename": "Rename a passkey `{id, name}` (session required inside the handler).",
    "POST /auth/credentials/delete": "Delete a passkey `{id}`; the last one cannot be removed.",
}
